### ISSUE TITLE
Wijzig de index.html bestand onder templates

### ISSUE THREAD

**Issue by TuxGhost** [TuxGhost/TalenOefenen#1]
Toon op de index pagina een willekeur woord vanuit een taalbestand . (zie uw voorbeeld - franse les)

Hulp om dit bestand aan te passen vind je op de volgende link:
https://www.w3schools.com/html/

Belangrijkse tags  → _"paragraaf"_ voor het moment.

**Comment by SeaMonkey08** [comment]
_Er komt steeds een nieuw woord wanneer je refrecht. Ook komen er steeds drie antwoorden tevoorschijn, namelijk A, B, en C._ **Het plobleem hier is dat de vertaling van het gegeven frans woord steed antwoord 'A' is.**

**Comment by TuxGhost** [comment]
Zeker niet slecht tot nu toe.  Beschouw het nu zeker als een logica puzzel ;-) 

Je geeft ook aan dat het franswoord en nederlandswoord steeds 'hoeveelste' is
    fransWoord = fr[hoeveelste]
    nederlandsWoord = nl[hoeveelste]

Hoeveelste komt steeds overeen met antwoord A ;-)
Er zijn 3 mogelijke antwoorden => random.randint(0,2)
Ik zou ook kunnen zeggen dat er een fake3 mist, hoewel de veldbenaming dan weer als verwarrend kan beschouwd worden want er is er één juist..
Kan je verder met deze tips ?

De lengte van de array is hard coded (met andere woorden vaste waarde in het programma).  Hier kan je best ook een variabele gebruiken.  De lengte van een array kan je bepalen bijvoorbeeld met volgende commando bepalen: lengte = len(nl)
