### ISSUE TITLE
Herschrijf de index pagina 

### ISSUE THREAD

**Issue by SeaMonkey08** [TuxGhost/TalenOefenen#8]
Aan deze kan je beginnen nadat je de franse pagina hernoemt hebt.

je mag hier voor een mooie layout kiezen dmv csv

**Comment by TuxGhost** [comment]
Dit ziet er al zeer goed uit.

Ik stel voor om de links groter te maken (font/lettertype)

-De titel van de subpagina's frans, duits , engels mag eigenlijk de taal bevatten.
bv Quiz Frans, Quiz Engels, Quiz Duits.  

De tekst 'No list yet' zou ik eerder op de pagina zelf zetten. Persoonlijk kijk ik eerst naar de inhoud(=body) en minder naar de titel in de hoofdbalk.

Het is zeer goed gezien om een beetje taal afhankelijk te werken, maar ik voor dit soort zaken bij een hoofdtaal houden.  Nederlands of Engels.  De vragen zelf in de taal zelf natuurlijk.

In het html document kan je een taal specifieren:
bv <html lang="en"> of <html lang="nl">
en voor vlaams zelfs <html lang="nl-BE">
Visueel zal bovenstaand niets veranderen, maar technisch een extra punt opleveren ;-)

je mag ticket op todo of in progress zetten afhankelijk of je hier nog vragen over hebt en tijd hebt om hierop verder te werken.  En anders
